;;; leaf-db.el --- DB of packages managed by `leaf-manager'  -*- lexical-binding: t; -*-

;; Copyright (C) 2024-2024 pachicobue

;; Author: pachicobue <tigerssho@gmail.com>

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; Auto-generated by `leaf-manager'

;;; Code:

(leaf autorevert
    :doc "revert buffers when files on disk change"
    :tag "builtin"
    :added "2024-03-20"
    :custom ((auto-revert-interval . 1)
             (auto-revert-check-vc-info . t))
    :global-minor-mode global-auto-revert-mode)

  (leaf avy
    :doc "Jump to arbitrary positions in visible text and select text quickly."
    :req "emacs-24.1" "cl-lib-0.5"
    :tag "location" "point" "emacs>=24.1"
    :url "https://github.com/abo-abo/avy"
    :added "2024-03-20"
    :emacs>= 24.1
    :straight t)

  (leaf centaur-tabs
    :doc "Aesthetic, modern looking customizable tabs plugin"
    :req "emacs-24.4" "powerline-2.4" "cl-lib-0.5"
    :tag "out-of-MELPA" "emacs>=24.4"
    :url "https://github.com/ema2159/centaur-tabs"
    :added "2024-03-20"
    :emacs>= 24.4
    :straight t
    :init
    (defun my/centaur-tabs-buffer-groups-function nil
      (list
       (cond
        ((string-equal "*dashboard*"
                       (buffer-name))
         "DashBoard")
        ((string-equal "*"
                       (substring
                        (buffer-name)
                        0 1))
         "Emacs")
        ((derived-mode-p 'vterm-mode)
         "Terminal")
        ((derived-mode-p 'dired-mode)
         "Directory")
        (t "Editing"))))

    :custom ((centaur-tabs-style . "alternate")
             (centaur-tabs-height . 30)
             (centaur-tabs-set-icons . t)
             (centaur-tabs-set-bar quote under)
             (x-underline-at-descent-line . t)
             (centaur-tabs-set-modified-marker . t)
             (centaur-tabs-cycle-scope quote tabs)
             (centaur-tabs-buffer-groups-function function my/centaur-tabs-buffer-groups-function))
    :global-minor-mode t)

  (leaf consult
    :doc "Consulting completing-read"
    :req "emacs-27.1" "compat-29.1.4.4"
    :tag "completion" "files" "matching" "emacs>=27.1"
    :url "https://github.com/minad/consult"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t)

  (leaf copilot
    :doc "An unofficial Copilot plugin for Emacs"
    :req "emacs-27.2" "s-1.12.0" "dash-2.19.1" "editorconfig-0.8.2" "jsonrpc-1.0.14" "f-0.20.0"
    :tag "out-of-MELPA" "copilot" "convenience" "emacs>=27.2"
    :url "https://github.com/copilot-emacs/copilot.el"
    :added "2024-03-20"
    :emacs>= 27.2
    :require t
    :init
    (defun my/copilot-tab nil
      (interactive)
      (or
       (copilot-accept-completion)
       (indent-for-tab-command)))

    :straight (copilot :type git :host github :repo "copilot-emacs/copilot.el")
    :hook (prog-mode-hook . copilot-mode)
    :custom (copilot-indent-offset-warning-disable . t))

  (leaf display-line-numbers
    :doc "interface for display-line-numbers"
    :tag "builtin"
    :added "2024-03-20"
    :custom (display-line-numbers-width . 4)
    :global-minor-mode global-display-line-numbers-mode)

  (leaf evil
    :doc "extensible vi layer"
    :tag "vim" "emulation"
    :url "https://github.com/emacs-evil/evil"
    :added "2024-03-20"
    :straight t
    :custom ((evil-cross-lines . t)
             (evil-respect-visual-line-mode . t)
             (evil-want-fine-undo . t)
             (evil-normal-state-cursor quote box)
             (evil-motion-state-cursor quote box)
             (evil-disable-insert-state-bindings . t))
    :global-minor-mode t)

  (leaf evil-goggles
    :doc "Add a visual hint to evil operations"
    :req "emacs-24.4" "evil-1.0.0"
    :tag "visual" "vim" "evil" "emulations" "emacs>=24.4"
    :url "http://github.com/edkolev/evil-goggles"
    :added "2024-03-20"
    :emacs>= 24.4
    :after evil
    :straight t
    :config
    (evil-goggles-use-diff-faces)
    :global-minor-mode t)

  (leaf evil-numbers
    :after evil
    :straight t)

  (leaf evil-surround
    :doc "emulate surround.vim from Vim"
    :req "evil-1.2.12"
    :tag "evil" "vi" "emulation"
    :url "https://elpa.nongnu.org/nongnu/evil-surround.html"
    :added "2024-03-20"
    :after evil
    :straight t
    :global-minor-mode global-evil-surround-mode)

  (leaf exec-path-from-shell
    :doc "Get environment variables such as $PATH from the shell"
    :req "emacs-24.1" "cl-lib-0.6"
    :tag "environment" "unix" "emacs>=24.1"
    :url "https://github.com/purcell/exec-path-from-shell"
    :added "2024-03-20"
    :emacs>= 24.1
    :straight t
    :custom ((exec-path-from-shell-arguments)
             (exec-path-from-shell-warn-duration-millis . 2000))
    :config
    (exec-path-from-shell-copy-envs
     '("PATH" "CXX_COMPILER" "CXX_COMMON_OPTIONS" "CXX_DEBUG_OPTIONS" "CXX_RELEASE_OPTIONS"))
    :require t)

  (leaf fontaine
    :doc "Set font configurations using presets"
    :req "emacs-27.1"
    :tag "emacs>=27.1"
    :url "https://git.sr.ht/~protesilaos/fontaine"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :custom (fontaine-presets quote
                              ((regular :default-familly "Source Code Pro" :default-height 120 :default-weight regular)))
    :config
    (fontaine-set-preset 'regular)
    :global-minor-mode t)

  (leaf general
    :doc "Convenience wrappers for keybindings."
    :req "emacs-24.4" "cl-lib-0.5"
    :tag "out-of-MELPA" "keys" "keybindings" "leader" "evil" "vim" "emacs>=24.4"
    :url "https://github.com/noctuid/general.el"
    :added "2024-03-20"
    :emacs>= 24.4
    :require t
    :straight t
    :config
    (general-evil-setup))

  (leaf key-chord
    :doc "map pairs of simultaneously pressed keys to commands"
    :req "emacs-24"
    :tag "out-of-MELPA" "input" "chord" "keyboard" "emacs>=24"
    :added "2024-03-20"
    :emacs>= 24
    :require t
    :straight t
    :custom (key-chord-two-keys-delay . 0.2)
    :global-minor-mode t)

;;  (leaf lsp-bridge
;;    :tag "out-of-MELPA"
;;    :added "2024-03-23"
;;    :straight (lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge" :files
;;                          (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
;;                          :build
;;                          (:not compile))
;;    :after yasnippet
;;    :init
;;    (global-lsp-bridge-mode)
;;    :custom ((lsp-bridge-python-multi-lsp-server . "pyright_ruff")
;;             (lsp-bridge-enable-completion-in-string . t)
;;             (lsp-bridge-enable-inlay-hint . t)
;;             (lsp-bridge-enable-org-babel . t)
;;             (acm-enable-icon . t)
;;             (acm-enable-copilot)
;;             (acm-enable-preview . t)
;;             (acm-enable-yas . t)
;;             (acm-backend-search-file-words)
;;             (acm-backend-lsp-enable-auto-import)))

  (leaf marginalia
    :doc "Enrich existing commands with completion annotations"
    :req "emacs-27.1" "compat-29.1.4.4"
    :tag "completion" "matching" "help" "docs" "emacs>=27.1"
    :url "https://github.com/minad/marginalia"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :global-minor-mode t)

  (leaf markdown-mode
    :doc "Major mode for Markdown-formatted text"
    :req "emacs-27.1"
    :tag "itex" "github flavored markdown" "markdown" "emacs>=27.1"
    :url "https://jblevins.org/projects/markdown-mode/"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :mode ("\\.md\\'" . gfm-mode)
    :custom ((markdown-command quote
                               ("pandoc" "--from=markdown" "--to=html39"))
             (markdown-fontify-code-blocks-natively . t)
             (markdown-enable-math . t)
             (markdown-header-scaling . t)
             (markdown-indent-on-enter quote indent-and-new-item)))

  (leaf minions
    :doc "A minor-mode menu for the mode line"
    :req "emacs-25.2" "compat-29.1.4.1"
    :tag "out-of-MELPA" "convenience" "emacs>=25.2"
    :url "https://github.com/tarsius/minions"
    :added "2024-03-20"
    :emacs>= 25.2
    :require t
    :straight t
    :custom (minions-mode-line-lighter . "[+]")
    :global-minor-mode minions-mode)

  (leaf modus-themes
    :doc "Elegant, highly legible and customizable themes"
    :req "emacs-27.1"
    :tag "accessibility" "theme" "faces" "emacs>=27.1"
    :url "https://github.com/protesilaos/modus-themes"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :commands modus-themes-load-theme
    :custom ((modus-themes-custom-auto-reload . t)
             (modus-themes-disable-other-themes . t))
    :init
    (modus-themes-load-theme 'modus-vivendi-tinted))

  (leaf mwim
    :doc "Switch between the beginning/end of line or code"
    :tag "out-of-MELPA" "convenience"
    :url "https://github.com/alezost/mwim.el"
    :added "2024-03-20"
    :require t
    :straight t)

  (leaf nerd-icons
    :doc "Emacs Nerd Font Icons Library"
    :req "emacs-24.3"
    :tag "out-of-MELPA" "lisp" "emacs>=24.3"
    :url "https://github.com/rainstormstudio/nerd-icons.el"
    :added "2024-03-20"
    :emacs>= 24.3
    :require t
    :straight t
    :custom ((centaur-tabs-icon-type quote nerd-icons)))

  (leaf orderless
    :doc "Completion style for matching regexps in any order"
    :req "emacs-26.1"
    :tag "extensions" "emacs>=26.1"
    :url "https://github.com/oantolin/orderless"
    :added "2024-03-20"
    :emacs>= 26.1
    :straight t
    :custom ((completion-styles quote
                                (orderless basic))
             (completion-category-defaults)
             (completion-category-overrides)))

  (leaf recentf
    :doc "keep track of recently opened files"
    :tag "builtin"
    :added "2024-03-20"
    :custom (recentf-max-saved-items . 1000) (recentf-auto-cleanup quote never)
    :global-minor-mode t)

  (leaf saveplace
    :doc "automatically save place in files"
    :tag "builtin"
    :added "2024-03-20"
    :global-minor-mode save-place-mode)

  (leaf server
    :doc "Lisp code for GNU Emacs running as server process"
    :tag "builtin"
    :added "2024-03-20"
    :commands (server-running-p)
    :unless (server-running-p)
    :config
    (server-start))

  (leaf smooth-scroll
    :doc "Minor mode for smooth scrolling and in-place scrolling."
    :tag "out-of-MELPA" "frames" "emulations" "convenience"
    :url "http://www.emacswiki.org/emacs/download/smooth-scroll.el"
    :added "2024-03-20"
    :require t
    :straight t
    :custom (smooth-scroll/vscroll-step-size . 10)
    :global-minor-mode smooth-scroll-mode)

  (leaf treesit
    :doc "tree-sitter utilities"
    :tag "builtin" "languages" "tree-sitter" "treesit"
    :added "2024-03-23"
    :custom ((treesit-font-lock-level . 4)))

  (leaf treesit-auto
    :straight t
    :custom ((treesit-auto-install quote prompt)
             (treesit-auto-add-to-auto-mode-alist quote all))
    :global-minor-mode global-treesit-auto-mode)

  (leaf vertico
    :doc "VERTical Interactive COmpletion"
    :req "emacs-27.1" "compat-29.1.4.4"
    :tag "completion" "matching" "files" "convenience" "emacs>=27.1"
    :url "https://github.com/minad/vertico"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :custom (vertico-preselect quote prompt)
    :global-minor-mode t)

  (leaf vundo
    :doc "Visual undo tree"
    :req "emacs-28.1"
    :tag "editing" "text" "undo" "emacs>=28.1"
    :url "https://github.com/casouri/vundo"
    :added "2024-03-20"
    :emacs>= 28.1
    :straight t)

  (leaf which-key
    :doc "Display available keybindings in popup"
    :req "emacs-24.4"
    :tag "emacs>=24.4"
    :url "https://github.com/justbur/emacs-which-key"
    :added "2024-03-20"
    :emacs>= 24.4
    :straight t
    :global-minor-mode t)

  (leaf yasnippet
    :doc "Yet another snippet extension for Emacs"
    :req "cl-lib-0.5" "emacs-24.4"
    :tag "emulation" "convenience" "emacs>=24.4"
    :url "http://github.com/joaotavora/yasnippet"
    :added "2024-03-23"
    :emacs>= 24.4
    :straight t
    :require t
    :global-minor-mode yas-global-mode)(prog1 'emacs)

(leaf leaf-manager
  :straight t
  :custom ((leaf-manager-file . my/leaf-db-file)
           (leaf-manager-template-feature-name . "leaf-db")
           (leaf-manager-template-summary . "DB of packages managed by `leaf-manager'")
           (leaf-manager-template-commentary . ";; Auto-generated by `leaf-manager'")
           (leaf-manager-template-copyright-from . "2024")
           (leaf-manager-template-local-variables . ";; indent-tabs-mode: nil"))
  :config
  (leaf autorevert
    :doc "revert buffers when files on disk change"
    :tag "builtin"
    :added "2024-03-20"
    :custom ((auto-revert-interval . 1)
             (auto-revert-check-vc-info . t))
    :global-minor-mode global-auto-revert-mode)

  (leaf avy
    :doc "Jump to arbitrary positions in visible text and select text quickly."
    :req "emacs-24.1" "cl-lib-0.5"
    :tag "location" "point" "emacs>=24.1"
    :url "https://github.com/abo-abo/avy"
    :added "2024-03-20"
    :emacs>= 24.1
    :straight t)

  (leaf centaur-tabs
    :doc "Aesthetic, modern looking customizable tabs plugin"
    :req "emacs-24.4" "powerline-2.4" "cl-lib-0.5"
    :tag "out-of-MELPA" "emacs>=24.4"
    :url "https://github.com/ema2159/centaur-tabs"
    :added "2024-03-20"
    :emacs>= 24.4
    :straight t
    :init
    (defun my/centaur-tabs-buffer-groups-function nil
      (list
       (cond
        ((string-equal "*dashboard*"
                       (buffer-name))
         "DashBoard")
        ((string-equal "*"
                       (substring
                        (buffer-name)
                        0 1))
         "Emacs")
        ((derived-mode-p 'vterm-mode)
         "Terminal")
        ((derived-mode-p 'dired-mode)
         "Directory")
        (t "Editing"))))

    :custom ((centaur-tabs-style . "alternate")
             (centaur-tabs-height . 30)
             (centaur-tabs-set-icons . t)
             (centaur-tabs-set-bar quote under)
             (x-underline-at-descent-line . t)
             (centaur-tabs-set-modified-marker . t)
             (centaur-tabs-cycle-scope quote tabs)
             (centaur-tabs-buffer-groups-function function my/centaur-tabs-buffer-groups-function))
    :global-minor-mode t)

  (leaf consult
    :doc "Consulting completing-read"
    :req "emacs-27.1" "compat-29.1.4.4"
    :tag "completion" "files" "matching" "emacs>=27.1"
    :url "https://github.com/minad/consult"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t)

 ;; (leaf copilot
 ;;   :doc "An unofficial Copilot plugin for Emacs"
 ;;   :req "emacs-27.2" "s-1.12.0" "dash-2.19.1" "editorconfig-0.8.2" "jsonrpc-1.0.14" "f-0.20.0"
 ;;   :tag "out-of-MELPA" "copilot" "convenience" "emacs>=27.2"
 ;;   :url "https://github.com/copilot-emacs/copilot.el"
 ;;   :added "2024-03-20"
 ;;   :emacs>= 27.2
 ;;   :require t
 ;;   :init
 ;;   (defun my/copilot-tab nil
 ;;     (interactive)
 ;;     (or
 ;;      (copilot-accept-completion)
 ;;      (indent-for-tab-command)))
 ;;   :straight (copilot :type git :host github :repo "copilot-emacs/copilot.el")
 ;;   :hook (prog-mode-hook . copilot-mode)
 ;;   :custom (copilot-indent-offset-warning-disable . t))

  (leaf display-line-numbers
    :doc "interface for display-line-numbers"
    :tag "builtin"
    :added "2024-03-20"
    :custom (display-line-numbers-width . 4)
    :global-minor-mode global-display-line-numbers-mode)

  (leaf evil
    :doc "extensible vi layer"
    :tag "vim" "emulation"
    :url "https://github.com/emacs-evil/evil"
    :added "2024-03-20"
    :straight t
     :custom ((evil-cross-lines . t)
             (evil-respect-visual-line-mode . t)
             (evil-want-fine-undo . t)
             (evil-normal-state-cursor quote box)
             (evil-motion-state-cursor quote box)
             (evil-disable-insert-state-bindings . t))
    :global-minor-mode t)

  (leaf evil-goggles
    :doc "Add a visual hint to evil operations"
    :req "emacs-24.4" "evil-1.0.0"
    :tag "visual" "vim" "evil" "emulations" "emacs>=24.4"
    :url "http://github.com/edkolev/evil-goggles"
    :added "2024-03-20"
    :emacs>= 24.4
    :after evil
    :straight t
    :config
    (evil-goggles-use-diff-faces)
    :global-minor-mode t)
    

  (leaf evil-numbers
    :after evil
    :straight t)

  (leaf evil-surround
    :doc "emulate surround.vim from Vim"
    :req "evil-1.2.12"
    :tag "evil" "vi" "emulation"
    :url "https://elpa.nongnu.org/nongnu/evil-surround.html"
    :added "2024-03-20"
    :after evil
    :straight t
    :global-minor-mode global-evil-surround-mode)

  (leaf exec-path-from-shell
    :doc "Get environment variables such as $PATH from the shell"
    :req "emacs-24.1" "cl-lib-0.6"
    :tag "environment" "unix" "emacs>=24.1"
    :url "https://github.com/purcell/exec-path-from-shell"
    :added "2024-03-20"
    :emacs>= 24.1
    :straight t
    :custom ((exec-path-from-shell-arguments)
             (exec-path-from-shell-warn-duration-millis . 2000))
    :config
    (exec-path-from-shell-copy-envs
     '("PATH" "CXX_COMPILER" "CXX_COMMON_OPTIONS" "CXX_DEBUG_OPTIONS" "CXX_RELEASE_OPTIONS"))
    :require t)

  (leaf fontaine
    :doc "Set font configurations using presets"
    :req "emacs-27.1"
    :tag "emacs>=27.1"
    :url "https://git.sr.ht/~protesilaos/fontaine"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :custom (fontaine-presets quote
                              ((regular :default-familly "Source Code Pro" :default-height 120 :default-weight regular)))
    :config
    (fontaine-set-preset 'regular)
    :global-minor-mode t)

  (leaf general
    :doc "Convenience wrappers for keybindings."
    :req "emacs-24.4" "cl-lib-0.5"
    :tag "out-of-MELPA" "keys" "keybindings" "leader" "evil" "vim" "emacs>=24.4"
    :url "https://github.com/noctuid/general.el"
    :added "2024-03-20"
    :emacs>= 24.4
    :require t
    :straight t
    :config
    (general-evil-setup))

  (leaf key-chord
    :doc "map pairs of simultaneously pressed keys to commands"
    :req "emacs-24"
    :tag "out-of-MELPA" "input" "chord" "keyboard" "emacs>=24"
    :added "2024-03-20"
    :emacs>= 24
    :require t
    :straight t
    :custom (key-chord-two-keys-delay . 0.2)
    :global-minor-mode t)

  (leaf lsp-bridge
    :tag "out-of-MELPA"
    :added "2024-03-23"
    :straight (lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge" :files
                          (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
                          :build
                          (:not compile))
    :after yasnippet
    :init
    (global-lsp-bridge-mode)
    :custom ((lsp-bridge-python-multi-lsp-server . "pyright_ruff")
             (lsp-bridge-enable-completion-in-string . t)
             (lsp-bridge-enable-inlay-hint . t)
             (lsp-bridge-enable-org-babel . t)
             (acm-enable-icon . t)
             (acm-enable-copilot)
             (acm-enable-preview . t)
             (acm-enable-yas . t)
             (acm-backend-search-file-words)
             (acm-backend-lsp-enable-auto-import)))

  (leaf marginalia
    :doc "Enrich existing commands with completion annotations"
    :req "emacs-27.1" "compat-29.1.4.4"
    :tag "completion" "matching" "help" "docs" "emacs>=27.1"
    :url "https://github.com/minad/marginalia"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :global-minor-mode t)

  (leaf markdown-mode
    :doc "Major mode for Markdown-formatted text"
    :req "emacs-27.1"
    :tag "itex" "github flavored markdown" "markdown" "emacs>=27.1"
    :url "https://jblevins.org/projects/markdown-mode/"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :mode ("\\.md\\'" . gfm-mode)
    :custom ((markdown-command quote
                               ("pandoc" "--from=markdown" "--to=html39"))
             (markdown-fontify-code-blocks-natively . t)
             (markdown-enable-math . t)
             (markdown-header-scaling . t)
             (markdown-indent-on-enter quote indent-and-new-item)))

  (leaf minions
    :doc "A minor-mode menu for the mode line"
    :req "emacs-25.2" "compat-29.1.4.1"
    :tag "out-of-MELPA" "convenience" "emacs>=25.2"
    :url "https://github.com/tarsius/minions"
    :added "2024-03-20"
    :emacs>= 25.2
    :require t
    :straight t
    :custom (minions-mode-line-lighter . "[+]")
    :global-minor-mode minions-mode)

  (leaf modus-themes
    :doc "Elegant, highly legible and customizable themes"
    :req "emacs-27.1"
    :tag "accessibility" "theme" "faces" "emacs>=27.1"
    :url "https://github.com/protesilaos/modus-themes"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :commands modus-themes-load-theme
    :custom ((modus-themes-custom-auto-reload . t)
             (modus-themes-disable-other-themes . t))
    :init
    (modus-themes-load-theme 'modus-vivendi-tinted))

  (leaf mwim
    :doc "Switch between the beginning/end of line or code"
    :tag "out-of-MELPA" "convenience"
    :url "https://github.com/alezost/mwim.el"
    :added "2024-03-20"
    :require t
    :straight t)

  (leaf nerd-icons
    :doc "Emacs Nerd Font Icons Library"
    :req "emacs-24.3"
    :tag "out-of-MELPA" "lisp" "emacs>=24.3"
    :url "https://github.com/rainstormstudio/nerd-icons.el"
    :added "2024-03-20"
    :emacs>= 24.3
    :require t
    :straight t
    :custom ((centaur-tabs-icon-type quote nerd-icons)))

  (leaf orderless
    :doc "Completion style for matching regexps in any order"
    :req "emacs-26.1"
    :tag "extensions" "emacs>=26.1"
    :url "https://github.com/oantolin/orderless"
    :added "2024-03-20"
    :emacs>= 26.1
    :straight t
    :custom ((completion-styles quote
                                (orderless basic))
             (completion-category-defaults)
             (completion-category-overrides)))

  (leaf recentf
    :doc "keep track of recently opened files"
    :tag "builtin"
    :added "2024-03-20"
    :custom (recentf-max-saved-items . 1000) (recentf-auto-cleanup quote never)
    :global-minor-mode t)

  (leaf saveplace
    :doc "automatically save place in files"
    :tag "builtin"
    :added "2024-03-20"
    :global-minor-mode save-place-mode)

  (leaf server
    :doc "Lisp code for GNU Emacs running as server process"
    :tag "builtin"
    :added "2024-03-20"
    :commands (server-running-p)
    :unless (server-running-p)
    :config
    (server-start))

  (leaf smooth-scroll
    :doc "Minor mode for smooth scrolling and in-place scrolling."
    :tag "out-of-MELPA" "frames" "emulations" "convenience"
    :url "http://www.emacswiki.org/emacs/download/smooth-scroll.el"
    :added "2024-03-20"
    :require t
    :straight t
    :custom (smooth-scroll/vscroll-step-size . 10)
    :global-minor-mode smooth-scroll-mode)

  (leaf treesit
    :doc "tree-sitter utilities"
    :tag "builtin" "languages" "tree-sitter" "treesit"
    :added "2024-03-23"
    :custom ((treesit-font-lock-level . 4)))

  (leaf treesit-auto
    :straight t
    :custom ((treesit-auto-install quote prompt)
             (treesit-auto-add-to-auto-mode-alist quote all))
    :global-minor-mode global-treesit-auto-mode)

  (leaf vertico
    :doc "VERTical Interactive COmpletion"
    :req "emacs-27.1" "compat-29.1.4.4"
    :tag "completion" "matching" "files" "convenience" "emacs>=27.1"
    :url "https://github.com/minad/vertico"
    :added "2024-03-20"
    :emacs>= 27.1
    :straight t
    :custom (vertico-preselect quote prompt)
    :global-minor-mode t)

  (leaf vundo
    :doc "Visual undo tree"
    :req "emacs-28.1"
    :tag "editing" "text" "undo" "emacs>=28.1"
    :url "https://github.com/casouri/vundo"
    :added "2024-03-20"
    :emacs>= 28.1
    :straight t)

  (leaf which-key
    :doc "Display available keybindings in popup"
    :req "emacs-24.4"
    :tag "emacs>=24.4"
    :url "https://github.com/justbur/emacs-which-key"
    :added "2024-03-20"
    :emacs>= 24.4
    :straight t
    :global-minor-mode t)

  (leaf yasnippet
    :doc "Yet another snippet extension for Emacs"
    :req "cl-lib-0.5" "emacs-24.4"
    :tag "emulation" "convenience" "emacs>=24.4"
    :url "http://github.com/joaotavora/yasnippet"
    :added "2024-03-23"
    :emacs>= 24.4
    :straight t
    :require t
    :global-minor-mode yas-global-mode))

(provide 'leaf-db)

;; Local Variables:
;; indent-tabs-mode: nil
;; End:

;;; leaf-db.el ends here
